version: '3.8'
services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile
    command: flask run --port ${PORT} --host 0.0.0.0
    volumes:
      - .:/usr/src/app/
    env_file:
      - .env
    environment:
      - DATABASE_URL=${DB_DRIVER:-postgresql}://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:5432/${DB_NAME}
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - db
  db:
    image: postgres:13-alpine
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - ${DB_PORT}:5432

volumes:
  postgres_data:
