"""empty message

Revision ID: 357370095280
Revises: 86cdbd5758ca
Create Date: 2022-02-10 17:07:09.283605

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '357370095280'
down_revision = '86cdbd5758ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('properties', sa.Column('real_estate_registration', sa.Integer(), nullable=False))
    op.add_column('properties', sa.Column('type_property', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('properties', 'type_property')
    op.drop_column('properties', 'real_estate_registration')
    # ### end Alembic commands ###
