"""empty message

Revision ID: 57b0d753b8cc
Revises: 357370095280
Create Date: 2022-02-12 20:00:02.602910

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57b0d753b8cc'
down_revision = '357370095280'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('properties', 'type_property')
    op.add_column('properties', sa.Column(
        'type_property', sa.Integer(), nullable=False, server_default='1'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('properties', 'type_property')
    op.add_column('properties', sa.Column('type_property', sa.VARCHAR(
        length=255), autoincrement=False, nullable=False, server_default='1'))
    # ### end Alembic commands ###
